export default {
  data(){
    return{
      goodsSort:[
        {
          value:'0',
          label:'蔬菜'
        },
        {
          value:'1',
          label:'水果'
        },
        {
          value:'2',
          label:'肉类'
        },
        {
          value:'3',
          label:'水产'
        },
        {
          value:'4',
          label:'干货'
        }
      ],
      SPFL:{
        '0':'蔬菜',
        '1':'水果',
        '2':'肉类',
        '3':'水产',
        '4':'干货',
      }
    }
  }
}